version: "3.4"

services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
  python:
    build:
      context: ./python
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongo
      - rabbit
  rabbit:
    build:
      context: ./rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"